version: '3.1'
services:
  db:
    image: postgres
    hostname: ff-db
    container_name: ff-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
