// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"context"
)

type Querier interface {
	GetBySKU(ctx context.Context, sku int32) (Stock, error)
	Reserve(ctx context.Context, arg []ReserveParams) *ReserveBatchResults
	ReserveCancel(ctx context.Context, arg []ReserveCancelParams) *ReserveCancelBatchResults
	ReserveRemove(ctx context.Context, arg []ReserveRemoveParams) *ReserveRemoveBatchResults
}

var _ Querier = (*Queries)(nil)
