// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package queries

import (
	"context"
)

const getBySKU = `-- name: GetBySKU :one
SELECT sku, available, reserved FROM stock
WHERE sku = $1
`

func (q *Queries) GetBySKU(ctx context.Context, sku int32) (Stock, error) {
	row := q.db.QueryRow(ctx, getBySKU, sku)
	var i Stock
	err := row.Scan(&i.Sku, &i.Available, &i.Reserved)
	return i, err
}
