// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package order

import (
	"context"
)

type Querier interface {
	AddItems(ctx context.Context, arg AddItemsParams) error
	Create(ctx context.Context, userID int64) (int64, error)
	GetByID(ctx context.Context, orderID int64) ([]GetByIDRow, error)
	SetStatus(ctx context.Context, arg SetStatusParams) error
}

var _ Querier = (*Queries)(nil)
