// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batch.go

package stock

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const reserve = `-- name: Reserve :batchone
UPDATE stock SET reserved = $2
WHERE sku = $1 AND count-reserved >= $2
RETURNING sku
`

type ReserveBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type ReserveParams struct {
	Sku      int64 `json:"sku"`
	Reserved int64 `json:"reserved"`
}

func (q *Queries) Reserve(ctx context.Context, arg []ReserveParams) *ReserveBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Sku,
			a.Reserved,
		}
		batch.Queue(reserve, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &ReserveBatchResults{br, len(arg), false}
}

func (b *ReserveBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var sku int64
		if b.closed {
			if f != nil {
				f(t, sku, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&sku)
		if f != nil {
			f(t, sku, err)
		}
	}
}

func (b *ReserveBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const reserveCancel = `-- name: ReserveCancel :batchone
UPDATE stock SET reserved = reserved-$2
WHERE sku = $1 AND reserved >= $2
RETURNING sku
`

type ReserveCancelBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type ReserveCancelParams struct {
	Sku      int64 `json:"sku"`
	Reserved int64 `json:"reserved"`
}

func (q *Queries) ReserveCancel(ctx context.Context, arg []ReserveCancelParams) *ReserveCancelBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Sku,
			a.Reserved,
		}
		batch.Queue(reserveCancel, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &ReserveCancelBatchResults{br, len(arg), false}
}

func (b *ReserveCancelBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var sku int64
		if b.closed {
			if f != nil {
				f(t, sku, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&sku)
		if f != nil {
			f(t, sku, err)
		}
	}
}

func (b *ReserveCancelBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const reserveRemove = `-- name: ReserveRemove :batchone
UPDATE stock SET (count, reserved) = (count-$2, reserved-$2)
WHERE sku = $1 AND count >= $2 AND reserved >= $2
RETURNING sku
`

type ReserveRemoveBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type ReserveRemoveParams struct {
	Sku   int64 `json:"sku"`
	Count int64 `json:"count"`
}

func (q *Queries) ReserveRemove(ctx context.Context, arg []ReserveRemoveParams) *ReserveRemoveBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Sku,
			a.Count,
		}
		batch.Queue(reserveRemove, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &ReserveRemoveBatchResults{br, len(arg), false}
}

func (b *ReserveRemoveBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var sku int64
		if b.closed {
			if f != nil {
				f(t, sku, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&sku)
		if f != nil {
			f(t, sku, err)
		}
	}
}

func (b *ReserveRemoveBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
