// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package stock

type Stock struct {
	Sku      int64 `json:"sku"`
	Count    int64 `json:"count"`
	Reserved int64 `json:"reserved"`
}
