services:
  cart:
    image: cart
    build: ./cart/
    ports:
      - "8082:8080"
    depends_on:
      - loms
  loms:
    image: loms
    build: ./loms/
    ports:
      - "8083:8080"
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
  db:
    image: postgres:17.2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./db/config:/config
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/.docker/postgresql/data:/var/lib/postgresql/data
