// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package queries

import (
	"context"
)

const add = `-- name: Add :exec
INSERT INTO cart (user_id, sku, count) VALUES ($1, $2, $3)
ON CONFLICT (user_id, sku) DO UPDATE SET count = $3
`

type AddParams struct {
	UserID int64
	Sku    int32
	Count  int32
}

func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.Exec(ctx, add, arg.UserID, arg.Sku, arg.Count)
	return err
}

const clear = `-- name: Clear :exec
DELETE FROM cart WHERE user_id = $1
`

func (q *Queries) Clear(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clear, userID)
	return err
}

const delete = `-- name: Delete :exec
DELETE FROM cart WHERE user_id = $1 AND sku = $2
`

type DeleteParams struct {
	UserID int64
	Sku    int32
}

func (q *Queries) Delete(ctx context.Context, arg DeleteParams) error {
	_, err := q.db.Exec(ctx, delete, arg.UserID, arg.Sku)
	return err
}

const list = `-- name: List :many
SELECT user_id, sku, count FROM cart WHERE user_id = $1
`

func (q *Queries) List(ctx context.Context, userID int64) ([]Cart, error) {
	rows, err := q.db.Query(ctx, list, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cart
	for rows.Next() {
		var i Cart
		if err := rows.Scan(&i.UserID, &i.Sku, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
