// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"context"
)

type Querier interface {
	Add(ctx context.Context, arg AddParams) error
	Clear(ctx context.Context, userID int64) error
	Delete(ctx context.Context, arg DeleteParams) error
	List(ctx context.Context, userID int64) ([]Cart, error)
}

var _ Querier = (*Queries)(nil)
